### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tuvqlu** [ErikPDev/AdvanceDeaths#20]
1. Leaderboards do not work 
2. Kill phrases don’t work 
3. Nothing basically works

**Comment by ErikPDev** [comment]
Hey!
I’m currently overseas and I can’t code on my phone lol.

Which version of pocketmine are you using?

**Comment by Tuvqlu** [comment]
Sure! I really want this plugin because it would make my server a lot more fun! So, I am using pocketmine 4.07 or whatever the most recent version is. Thankyou for the quick reply!

**Comment by Tuvqlu** [comment]
I took it off my server becuase it was getting frustrating not working, but today I’ll try it again and send you the log. I just added some kill phrases, and leaderboards.

**Comment by ErikPDev** [comment]
> I took it off my server becuase it was getting frustrating not working, but today I’ll try it again and send you the log. I just added some kill phrases, and leaderboards.

Alright!
Take your time :p

**Comment by Tuvqlu** [comment]
Yeah, have you tested out those features in the current version, and they work?

**Comment by ErikPDev** [comment]
> Yeah, have you tested out those features in the current version, and they work?

I’ve tested AdvanceDeaths with PM4 to update it. It works fine, maybe there’s an api change but I’m not sure since I don’t have my laptop with me for over 3 weeks.

**Comment by Tuvqlu** [comment]
Does it require database ?

**Comment by ErikPDev** [comment]
> Does it require database ?

It uses a SQLite database by default located on the configuration folder of AdvanceDeaths.

**Comment by ErikPDev** [comment]
> I haven’t added any databases, do I need to download mysql or SQLite for it to work?

It should work by default.

**Comment by Tuvqlu** [comment]
Here’s the crash :/
![AE207DE8-54DB-4D4B-A43E-239D00D2481B](https://user-images.githubusercontent.com/98550458/152890467-559a4ffa-e6b8-432c-9292-ccfedf166d77.jpeg)

**Comment by ErikPDev** [comment]
Oops, I forgot to change Level to World.

Unfortunately, I can’t code atm but I’ll figure something out.

**Comment by ErikPDev** [comment]
Hey @Tuvqlu, may you test the latest build?
https://poggit.pmmp.io/ci/ErikPDev/AdvanceDeaths/AdvanceDeaths/dev:93

**Comment by Tuvqlu** [comment]
Sure I hope it works : D. Also, does the scoreboard tags work with scorehud for api 4.0.0?Hope so  😄

**Comment by ErikPDev** [comment]
> Sure I hope it works : D. Also, does the scoreboard tags work with scorehud for api 4.0.0?Hope so 😄

Unfortunately, there isn’t any public scoreboard plugins on poggit for PM4 so I can’t implement a support for it yet.
ScoreHud is supported on PM3.

**Comment by Tuvqlu** [comment]
You should make a level system plugin that would be pretty cool

**Comment by Tuvqlu** [comment]
Uh 
![Uploading 77E21989-761C-41C8-89F1-FD2038E4A637.jpeg…]()

**Comment by ErikPDev** [comment]
?

**Comment by Tuvqlu** [comment]
![CF64366F-014F-45AD-8FCF-8F55686E29BE](https://user-images.githubusercontent.com/98550458/153402581-def30c00-4401-48ae-983c-6730a1a6ca33.jpeg)
Oh my bad, here.

**Comment by ErikPDev** [comment]
Are you using the latest release?
You should use the latest dev build.
https://poggit.pmmp.io/r/160983/AdvanceDeaths_dev-93.phar

**Comment by Tuvqlu** [comment]
Yes, i was using this: 
![FE8DBFAD-DED8-4F7B-A6F6-48498E43B0DE](https://user-images.githubusercontent.com/98550458/153413387-dd9856a0-8697-4a73-ae37-543e2766476e.jpeg)

**Comment by ErikPDev** [comment]
That error is different than the screenshot you sent me.
Looking into it

**Comment by ErikPDev** [comment]
Made some changes, may you try the latest dev build again?

**Comment by ErikPDev** [comment]
#97 actually

**Comment by Tuvqlu** [comment]
K just downloaded. Loading now. Should the kill phrases work as well? And do I need to enter a password and username for MySQL?

**Comment by Tuvqlu** [comment]
Okay!

**Comment by Tuvqlu** [comment]
We should apply for a world record of longest GitHub issue lol

**Comment by ErikPDev** [comment]
I’ve also noticed a bunch of other bugs which I’m not sure how I didn’t notice them.
I’ll fix them in 3-5 days.

**Comment by ErikPDev** [comment]
Yeah, I’ll have to completely update it to PM4 again. I’ll be back home at 3-5 days then I’m able to do it.

**Comment by ErikPDev** [comment]
Thanks, I'm back home now.
Try out this dev build https://poggit.pmmp.io/ci/ErikPDev/AdvanceDeaths/~/dev:98

**Comment by Tuvqlu** [comment]
Erik, one more crash, I think it's from the particles:![image](https://user-images.githubusercontent.com/98550458/153960696-4badfc5b-9197-416c-90f1-2255924ba210.jpeg)

**Comment by ErikPDev** [comment]
Fixed on the latest dev build

**Comment by ErikPDev** [comment]
Update me btw :p

**Comment by Tuvqlu** [comment]
Ofc bro 5 stars

**Comment by ErikPDev** [comment]
I meant if it's working or not

**Comment by Tuvqlu** [comment]
OHH lol I will

**Comment by Tuvqlu** [comment]
Still crashes ![image](https://user-images.githubusercontent.com/98550458/154373402-437ae8d9-3def-40cf-bf73-046f8256e710.jpeg)

**Comment by ErikPDev** [comment]
I'm officialy switching ide's.

> Still crashes ![image](https://user-images.githubusercontent.com/98550458/154373402-437ae8d9-3def-40cf-bf73-046f8256e710.jpeg)
I'm officially switching ide's.

**Comment by ErikPDev** [comment]
OKay, made a few visible changes in my ide. Try the latest build again :p

**Comment by ErikPDev** [comment]
Closing in a few hours due to inactivity
