### ISSUE TITLE
[Crash

### ISSUE THREAD

**Issue by Tuvqlu** [ErikPDev/AdvanceDeaths#24]
**Describe the bug**

crashes when joining !

**To Reproduce**
Explain here how to reproduce the bug in bullet points.

add plugin!

**Expected behavior**
A clear and concise description of what you expected to happen

plugin to work 
.

**Screenshots or Crash Dump**
If applicable, add screenshots, crash.pmmp.io or crash dumps to help explain your problem.

"Trying to access array offset on value of type null" (EXCEPTION) in "plugins/AdvanceDeaths_dev-117.phar/src/ErikPDev/AdvanceDeaths/ADMain" at line 79

**
]
 - PMMP Version: [e.g. 4.2.1]
 - PHP Version: [e.g. PHP 8.1]

**Additional context**

"Trying to access array offset on value of type null" (EXCEPTION) in "plugins/AdvanceDeaths_dev-117.phar/src/ErikPDev/AdvanceDeaths/ADMain" at line 79

**Comment by OP-D** [comment]
It appears your configuration is outdated. I’ll add a check for the configuration today.
Delete or rename your configuration to get the new ones.

**Comment by ErikPDev** [comment]
It appears your configuration is outdated, delete or rename your old one to fix it.

Your database can stay the same.
Fixed in the latest build.
