### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by logannn61** [ErikPDev/AdvanceDeaths#26]
**Describe the bug**
crash

**To Reproduce**
not sure as was not online

**Expected behavior**
server not to crash

**Screenshots or Crash Dump**
https://crash.pmmp.io/view/6305721

**Device Information**
 - OS: ios
 - MC: Latest ver
 
**Server Information (please complete the following information):**
 - OS: linux
 - PMMP Version: latest
 - PHP Version: PHP 8

**Comment by ErikPDev** [comment]
Fixed in the latest dev build.
