### ISSUE TITLE
[Epic Update Ideas] Level System

### ISSUE THREAD

**Issue by Tuvqlu** [ErikPDev/AdvanceDeaths#30]
**Is your feature request related to a problem? Please describe.**

NO

**Describe the solution you'd like**
- I think a level system would be super cool.
The more kills and kill streaks you get, the higher level you become, and each level you could unlock new kill phrases, kill effects / particles / and sounds and more. There could be sound for when you level up and scorehud tag!
- /leaderboard command where you could view a UI of each leaderboard

**Describe alternatives you've considered**
N / A

**Additional context**
N / A.

**Comment by ErikPDev** [comment]
I love this idea, I'll keep this issue open till I implement it. 
But, I'll be busy for a couple of weeks.

**Comment by Tuvqlu** [comment]
Yeah it would be so cool and there could be a /locker where you could see all unlocks and you could equip and see what you don’t have yet. There could also be like it says ur level in chat or under your name

**Comment by ErikPDev** [comment]
This idea is being worked on. 
I’ll post more information about this on Discord when available.

**Comment by ErikPDev** [comment]
I don't link the levels with the xp bar by default, I'll add an option for it tho.
