### ISSUE TITLE
[BUG] in version 4.0.1 of the plugin scorehud tags do not load

### ISSUE THREAD

**Issue by MG-TATSUMI** [ErikPDev/AdvanceDeaths#33]
**Describe the bug**

**To Reproduce**
Explain here how to reproduce the bug in bullet points.

**Expected behavior**

**Screenshots or Crash Dump**
If applicable, add screenshots, crash.pmmp.io or crash dumps to help explain your problem.

**Device Information**
 - Minecraft Version: [18.x.x]
 
**Server Information (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - PMMP Version: [e.g. 4.2.1]
 - PHP Version: [e.g. PHP 8.1]

**Additional context**

**Comment by ErikPDev** [comment]
Please fill the required value.
Uploady your scorehud.yml here.
