### ISSUE TITLE
Steal Option 

### ISSUE THREAD

**Issue by logannn61** [ErikPDev/AdvanceDeaths#34]
Add an option to steal a percentage of the other players money for example if set to 50% when they kill a player they will gain 50% of the victims money and the victim will lose 50% of their money.

**Comment by ErikPDev** [comment]
This feature is already added?

**Comment by logannn61** [comment]
Which build because the one I’m using when you kill someone with the percent option you will receive a percentage of your own money not the victims money

**Comment by ErikPDev** [comment]
> Which build because the one I’m using when you kill someone with the percent option you will receive a percentage of your own money not the victims money

Whoops. Looking into it.

**Comment by ErikPDev** [comment]
Looked into it but didn't think of it, cleaning up issues. Will be implemented later
