### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Missouriii** [ErikPDev/AdvanceDeaths#35]
**Describe the bug**
The Killstreak leaderboard does not spawn

**To Reproduce**
Create a kill streak leaderboard. 

**Expected behavior**
The leaderboard to spawn

**Screenshots or Crash Dump**
![image](https://user-images.githubusercontent.com/105463867/187319325-41b7baed-2cc1-462b-ac03-d2cc30991990.jpg)

**Device Information**
 - Minecraft Version: [1.19.21]
 

**Additional context**

**Comment by ErikPDev** [comment]
Fixed, I hope
