### ISSUE TITLE
Off topic, but please reply.

### ISSUE THREAD

**Issue by Wayder228** [ErikPDev/AdvanceDeaths#37]
Can you provide a link to your plugin's discord server?

**Comment by ErikPDev** [comment]
Sorry but I've deleted the AdvanceDeaths discord server.
My main focus nowadays is Server Hosting. (XenoHosts)
You can see more about XenoHosts [here](https://xenohosts.com).

XenoHosts Discord Server:
https://XenoHosts.com/discord
