### ISSUE TITLE
[BUG] Server crashing when killing someone with 100% playerMoney gain in config

### ISSUE THREAD

**Issue by TrinitroToluen0** [ErikPDev/AdvanceDeaths#38]
**Describe the bug**
This bug crashes the server when configuring the plugin to gain 100% of the money of the victim and killing someone

**To Reproduce**
1. Set the config like this:
```
onKillMoney:
  isEnabled: true
  disabled-worlds:
    - "World1"
    - "AntiKillMoneyWorld"
  type: "playerMoney" # Possible values = percent/amount/playerMoney
  valueType: "gain" # Possible values = lose/gain
  amount: 100
```
2. Kill someone
3. See the server crashing

**Expected behavior**
Kill someone and gain 100% of the money of the victim

**Screenshots or Crash Dump**
2024-03-28 [20:03:35.158] [Server thread/CRITICAL]: TypeError: "ErikPDev\AdvanceDeaths\listeners\moneyRelated\killMoney::modifyMoney(): Argument #2 ($amount) must be of type float, pocketmine\promise\Promise given, called in phar:///home/admin/Latam/plugins/AdvanceDeaths.phar/src/ErikPDev/AdvanceDeaths/listeners/moneyRelated/killMoney.php on line 70" (EXCEPTION) in "plugins/AdvanceDeaths.phar/src/ErikPDev/AdvanceDeaths/listeners/moneyRelated/killMoney" at line 32
--- Stack trace ---
  #0 plugins/AdvanceDeaths.phar/src/ErikPDev/AdvanceDeaths/listeners/moneyRelated/killMoney(70): ErikPDev\AdvanceDeaths\listeners\moneyRelated\killMoney->modifyMoney(object pocketmine\player\Player#186081, object pocketmine\promise\Promise#119547, string[4] gain)
  #1 pmsrc/src/promise/PromiseResolver(50): ErikPDev\AdvanceDeaths\listeners\moneyRelated\killMoney->ErikPDev\AdvanceDeaths\listeners\moneyRelated\{closure}(int 0)
  #2 plugins/AdvanceDeaths.phar/src/ErikPDev/AdvanceDeaths/utils/currencyManager(54): pocketmine\promise\PromiseResolver->resolve(int 0)
  #3 pmsrc/src/promise/PromiseResolver(50): ErikPDev\AdvanceDeaths\utils\currencyManager->ErikPDev\AdvanceDeaths\utils\{closure}(int 0)
  #4 plugins/BedrockEconomy.phar/src/cooldogedev/BedrockEconomy/api/type/BetaAPI(57): pocketmine\promise\PromiseResolver->resolve(int 0)
  #5 plugins/BedrockEconomy.phar/src/cooldogedev/BedrockEconomy/libs/_4e1ccda2437e95df/cooldogedev/libSQL/ConnectionPool(90): cooldogedev\BedrockEconomy\api\type\BetaAPI->cooldogedev\BedrockEconomy\api\type\{closure}(array[5])
  #6 pmsrc/src/TimeTrackingSleeperHandler(58): cooldogedev\BedrockEconomy\libs\_4e1ccda2437e95df\cooldogedev\libSQL\ConnectionPool->cooldogedev\BedrockEconomy\libs\_4e1ccda2437e95df\cooldogedev\libSQL\{closure}()
  #7 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
  #8 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
  #9 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #10 pmsrc/src/Server(1696): pocketmine\snooze\SleeperHandler->sleepUntil(float 1711656215.1392)
  #11 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
  #12 pmsrc/src/PocketMine(350): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[18] /home/admin/Latam/, string[26] /home/admin/Latam/plugins/)
  #13 pmsrc/src/PocketMine(373): pocketmine\server()
  #14 pmsrc(11): require(string[62] phar:///home/admin/Latam/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Device Information**
 - OS: Windows 11
 - Minecraft Version: 1.20.72
 
**Server Information (please complete the following information):**
 - OS: Debian 12
 - PMMP Version: 5.12.0
 - PHP Version: PHP 8.1

**Comment by ErikPDev** [comment]
Hi there! Thank you for reporting this bug but I've moved on from PocketMine development and I'm not planning to maintain this plugin.

However, I'll review your PR and give it a push
