### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Diedman9T** [ErikPDev/AdvanceDeaths#40]
It would be cool to add the ability for a message to be displayed above the player’s inventory (so as not to clog up the chat).  How can I implement this?  I opened every file in the plugin, but still couldn’t find the lines responsible for this...

**Comment by ErikPDev** [comment]
Hi there!
I'm not sure what you mean by displaying the message above the player's inventory. Perhaps, you meant above the hotbar where the item names are displayed( I forgot it's name ).

This [event](https://github.com/ErikPDev/AdvanceDeaths/blob/5e38c5d5edf6b31d596244ab0f9823df95d733d0/src/ErikPDev/AdvanceDeaths/ADMain.php#L191) is responsible for handling the player death events.

This [function](https://github.com/ErikPDev/AdvanceDeaths/blob/5e38c5d5edf6b31d596244ab0f9823df95d733d0/src/ErikPDev/AdvanceDeaths/ADMain.php#L202) sets the death message (which is seen in chat) and the [kill streak broadcasts](https://github.com/ErikPDev/AdvanceDeaths/blob/5e38c5d5edf6b31d596244ab0f9823df95d733d0/src/ErikPDev/AdvanceDeaths/ADMain.php#L226) can be seen here but can be disabled using the config.

You can create another plugin that sets the death message to null but sends the player the text using the way you would like. 
You'll have to set the [priority](https://forums.pmmp.io/threads/getting-your-priorities-straight.3382/) to high on that event as AdvanceDeaths sets it to low to be called the first.

You may also add this feature to AdvanceDeaths and make it configurable.
Users will be able to change back and forth using a key/value as such:
`announceDeath: false`
`showasblahblah: true`

**Comment by Diedman9T** [comment]
I understood the issue a little.  So, there is a sendMessage event, and there is a sendPopup.  So I propose in one of the updates to add the ability to display death messages not in chat, but as a Popup

**Comment by ErikPDev** [comment]
You can do that
Feel free to make a PR or a plugin
Best of luck!
