### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by EvilDevil1175** [ErikPDev/AdvanceDeaths#6]
add the format that gives you the kills you take 
{killer}[{kills}] killed {name}[{kills}] with {weapon}

**Comment by ErikPDev** [comment]
This will come out with the ScoreHUD and api update.

**Comment by ErikPDev** [comment]
Going to start working on this! Leaving this issue open for tracking.

**Comment by ErikPDev** [comment]
Database will be using sqlite3, I may or may not add support for "sql"

**Comment by ErikPDev** [comment]
This update is done. Uploading commit.
