### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by ErwanScraft** [ErikPDev/AdvanceDeaths#7]
I'm using version 53 of this plugin and found an error like this

![Screenshot_2021-09-22-17-30-57-328_com android chrome](https://user-images.githubusercontent.com/72255518/134328576-58f7c351-7009-4404-8dac-9a2800ca53f8.jpg)

**Comment by ErikPDev** [comment]
That was fast, I'm looking into the error.

**Comment by ErikPDev** [comment]
Fixed this Error on Version #55
https://poggit.pmmp.io/ci/ErikPDev/AdvanceDeaths/AdvanceDeaths/dev:55

**Comment by ErikPDev** [comment]
@ErwanScraft

**Comment by ErikPDev** [comment]
Does it work?

**Comment by ErwanScraft** [comment]
Yes bro it worked

**Comment by ErikPDev** [comment]
Awesome! What do you think of the plug-in?
-- 
Erik

**Comment by ErikPDev** [comment]
@ErwanScraft
